// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsKh8FaSO6Xf6aC0wctnFrDSKe0jUvrN4',
    appId: '1:716499073400:web:8b5707ac76626551eab08d',
    messagingSenderId: '716499073400',
    projectId: 'nexus-4a80c',
    authDomain: 'nexus-4a80c.firebaseapp.com',
    storageBucket: 'nexus-4a80c.appspot.com',
    measurementId: 'G-CK165M4E8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6NYFlzhLKH8EL1nIRYiy994qaf-Yc0U4',
    appId: '1:716499073400:android:cc5f2d58f4d815b2eab08d',
    messagingSenderId: '716499073400',
    projectId: 'nexus-4a80c',
    storageBucket: 'nexus-4a80c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPtKDTNXjNkaOMWOPPPIGPBK_knW_G6OA',
    appId: '1:716499073400:ios:0df046f76f54435aeab08d',
    messagingSenderId: '716499073400',
    projectId: 'nexus-4a80c',
    storageBucket: 'nexus-4a80c.appspot.com',
    iosBundleId: 'com.example.nexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPtKDTNXjNkaOMWOPPPIGPBK_knW_G6OA',
    appId: '1:716499073400:ios:0df046f76f54435aeab08d',
    messagingSenderId: '716499073400',
    projectId: 'nexus-4a80c',
    storageBucket: 'nexus-4a80c.appspot.com',
    iosBundleId: 'com.example.nexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsKh8FaSO6Xf6aC0wctnFrDSKe0jUvrN4',
    appId: '1:716499073400:web:2977436a6db6cf2eeab08d',
    messagingSenderId: '716499073400',
    projectId: 'nexus-4a80c',
    authDomain: 'nexus-4a80c.firebaseapp.com',
    storageBucket: 'nexus-4a80c.appspot.com',
    measurementId: 'G-PF5T9GT6CF',
  );
}
